### ISSUE TITLE
VPID behavior with MOV-TO-CR3 trapping

### ISSUE THREAD

**Issue by tklengyel** [Bareflank/hypervisor_example_vpid#4]
Hey guys,
I've been having a long discussion with Xen folks about VPID behavior when CPU-based CR3 loading is enabled (https://lists.xenproject.org/archives/html/xen-devel/2016-09/msg02164.html). Since Xen comes with a ton of baggage in regards of tagged TLB uses, this would be an interesting test-case for BareFlank.

So basically the question is, does the CPU perform TLB flushing automatically when MOV-TO-CR3 is trapped or not. The SDM doesn't explicitly say anything about this either way. On Xen right now there is a mandatory VPID flush when this happens, but as far as I can tell, it is not actually required. However, since there are a lot of unrelated flushes happening on Xen, it may be easier to validate the setup here.

For this I have the following questions:
1. Is it possible to perform pinning a VMCS with BareFlank to a physical core to avoid SMP migration?
2. Is it possible to pin a process to a specific VMCS?

If these tasks can somehow be done, then the experiment would be the following. Run two processes in parallel on the same physical core using the same VPID and enable MOV-TO-CR3 trapping. Both processes will map the same arbitrary virtual address with unique physical pages backing them and write unique canaries to their respective pages. In a busy-loop both continuously fetch this memory and compare it to the original value of their canary. The idea is that if MOV-TO-CR3 doesn't actually flush the TLB as it would normally, then eventually one of the two process' will hit the cached TLB entry of the other one.

Cheers,
Tamas

**Comment by rianquinn** [comment]
@tklengyel 

This sounds like a great use case for Bareflank as this is exactly the kind of thing this hypervisor was built for. 

Since we currently don't have support for moving a VMCS from one core to another, pinning a VMCS to a core works today. The challenge is #2 as we don't have the ability in their today, to create more than one VMCS for a core. That being said, I don't think it would take a lot of work to do this. Besides the fact that Bareflank is still in heavy development (so a lot of features are still missing), Bareflank itself is, and always will be geared towards providing the scaffolding for creating a hypervisor for research, specifically so that you don't inherit baggage (which is exactly the case your describing). That however means that when you want to test out and idea, you might have to write a bit of code to get things working. 

Testing out your idea with Bareflank should be pretty simple, but we'll need to figure out how to launch a VMCS tied to a specific process. Right now, you can IOCTL from a userspace process to start a VMCS, but the code is setup right now to prevent you from doing this twice, so you would simply need to add the logic to launch the second one, and swap based on the tests your trying to run. 

If your interested in trying this out, I would start by looking at BFM, as it's the userspace app that does the IOCTL, and you could probably just use this as is, but keep it running so that you can swap from one VMCS to another. It would be dirty.. but it would be enough to test your theory. The VPID and trapping on CR3 should be pretty trivial with Bareflank (just look at the examples). 

Let me know what you need from us. Besides the fact that this would be an awesome win for Bareflank to show how it can be used for this type of work, it's also a topic that I find very interesting. 😄

**Comment by rianquinn** [comment]
FYI, still working on the global flag and getting rid of the page fault. Once I get a free minute that is 😄 . I'll post my results as a repo on my personal page so that you can play around if you want. @tklengyel
